language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jack-evan/docker-react -f Dockerfile.dev .

script:
  #  - docker run jack-evan/docker-react
  - docker run -e CI=true jack-evan/docker-react npm run test



