language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jack-evan/docker-react -f Dockerfile.dev .

script:
  #  - docker run jack-evan/docker-react
  - docker run -e CI=true jack-evan/docker-react npm run test


deploy:
  provider: elasticbeanstalk 
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env" 
  bucket_name: "elasticbeanstalk-us-west-2-389010963264"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: \$aws-access-key
  secret_access_key: "$aws-secret-access-key"


